"""Comprehensive list of Romanian zones (cities + neighborhoods/sectors).
Used by seed.py to populate regions collection and by frontend dropdowns.

Each tuple: (country, city, zone) — zone is either a sector/cartier or quarter name.
"""

ROMANIAN_ZONES = [
    # București — 6 sectoare + cartiere principale
    ("România", "București", "Sector 1"),
    ("România", "București", "Sector 2"),
    ("România", "București", "Sector 3"),
    ("România", "București", "Sector 4"),
    ("România", "București", "Sector 5"),
    ("România", "București", "Sector 6"),
    ("România", "București", "Aviației"),
    ("România", "București", "Băneasa"),
    ("România", "București", "Berceni"),
    ("România", "București", "Crângași"),
    ("România", "București", "Colentina"),
    ("România", "București", "Dorobanți"),
    ("România", "București", "Drumul Taberei"),
    ("România", "București", "Floreasca"),
    ("România", "București", "Herăstrău"),
    ("România", "București", "Militari"),
    ("România", "București", "Pantelimon"),
    ("România", "București", "Pipera"),
    ("România", "București", "Primăverii"),
    ("România", "București", "Rahova"),
    ("România", "București", "Tineretului"),
    ("România", "București", "Titan"),
    ("România", "București", "Vitan"),
    ("România", "București", "Centrul Vechi"),

    # Cluj-Napoca
    ("România", "Cluj-Napoca", "Centru"),
    ("România", "Cluj-Napoca", "Mănăștur"),
    ("România", "Cluj-Napoca", "Mărăști"),
    ("România", "Cluj-Napoca", "Zorilor"),
    ("România", "Cluj-Napoca", "Grigorescu"),
    ("România", "Cluj-Napoca", "Gheorgheni"),
    ("România", "Cluj-Napoca", "Andrei Mureșanu"),
    ("România", "Cluj-Napoca", "Borhanci"),
    ("România", "Cluj-Napoca", "Bună Ziua"),
    ("România", "Cluj-Napoca", "Făget"),
    ("România", "Cluj-Napoca", "Iris"),
    ("România", "Cluj-Napoca", "Plopilor"),
    ("România", "Cluj-Napoca", "Someșeni"),
    ("România", "Cluj-Napoca", "Bulgaria"),

    # Timișoara
    ("România", "Timișoara", "Cetate"),
    ("România", "Timișoara", "Iosefin"),
    ("România", "Timișoara", "Elisabetin"),
    ("România", "Timișoara", "Fabric"),
    ("România", "Timișoara", "Mehala"),
    ("România", "Timișoara", "Dacia"),
    ("România", "Timișoara", "Soarelui"),
    ("România", "Timișoara", "Lipovei"),
    ("România", "Timișoara", "Aradului"),
    ("România", "Timișoara", "Calea Buziașului"),
    ("România", "Timișoara", "Calea Șagului"),
    ("România", "Timișoara", "Circumvalațiunii"),
    ("România", "Timișoara", "Steaua"),

    # Iași
    ("România", "Iași", "Centru"),
    ("România", "Iași", "Copou"),
    ("România", "Iași", "Tătărași"),
    ("România", "Iași", "Alexandru cel Bun"),
    ("România", "Iași", "Nicolina"),
    ("România", "Iași", "Păcurari"),
    ("România", "Iași", "Galata"),
    ("România", "Iași", "Țicău"),
    ("România", "Iași", "Bucium"),
    ("România", "Iași", "Dacia"),
    ("România", "Iași", "Mircea cel Bătrân"),

    # Constanța
    ("România", "Constanța", "Centru"),
    ("România", "Constanța", "Mamaia"),
    ("România", "Constanța", "Tomis Nord"),
    ("România", "Constanța", "Tomis Sud"),
    ("România", "Constanța", "Coiciu"),
    ("România", "Constanța", "Faleză Nord"),
    ("România", "Constanța", "Anadalchioi"),
    ("România", "Constanța", "Brotăcei"),
    ("România", "Constanța", "Inel I"),
    ("România", "Constanța", "Inel II"),
    ("România", "Constanța", "Km 4-5"),

    # Brașov
    ("România", "Brașov", "Centru"),
    ("România", "Brașov", "Schei"),
    ("România", "Brașov", "Astra"),
    ("România", "Brașov", "Răcădău"),
    ("România", "Brașov", "Tractorul"),
    ("România", "Brașov", "Bartolomeu"),
    ("România", "Brașov", "Stupini"),
    ("România", "Brașov", "Florilor"),
    ("România", "Brașov", "Noua"),
    ("România", "Brașov", "Valea Cetății"),

    # Craiova
    ("România", "Craiova", "Centru"),
    ("România", "Craiova", "Brazda lui Novac"),
    ("România", "Craiova", "Calea București"),
    ("România", "Craiova", "Craiovița Nouă"),
    ("România", "Craiova", "Rovine"),
    ("România", "Craiova", "Valea Roșie"),
    ("România", "Craiova", "1 Mai"),
    ("România", "Craiova", "Sărari"),

    # Galați
    ("România", "Galați", "Centru"),
    ("România", "Galați", "Țiglina I"),
    ("România", "Galați", "Țiglina II"),
    ("România", "Galați", "Țiglina III"),
    ("România", "Galați", "Micro 13"),
    ("România", "Galați", "Micro 14"),
    ("România", "Galați", "Micro 19"),
    ("România", "Galați", "Mazepa I"),
    ("România", "Galați", "Mazepa II"),
    ("România", "Galați", "Aurel Vlaicu"),

    # Ploiești
    ("România", "Ploiești", "Centru"),
    ("România", "Ploiești", "Vest"),
    ("România", "Ploiești", "Nord"),
    ("România", "Ploiești", "Sud"),
    ("România", "Ploiești", "Mihai Bravu"),
    ("România", "Ploiești", "Bereasca"),
    ("România", "Ploiești", "9 Mai"),
    ("România", "Ploiești", "Republicii"),

    # Oradea
    ("România", "Oradea", "Centru"),
    ("România", "Oradea", "Rogerius"),
    ("România", "Oradea", "Nufărul"),
    ("România", "Oradea", "Iosia"),
    ("România", "Oradea", "Velența"),
    ("România", "Oradea", "Vie"),
    ("România", "Oradea", "Olosig"),
    ("România", "Oradea", "Episcopia"),

    # Sibiu
    ("România", "Sibiu", "Centru"),
    ("România", "Sibiu", "Vasile Aaron"),
    ("România", "Sibiu", "Hipodrom"),
    ("România", "Sibiu", "Țiglari"),
    ("România", "Sibiu", "Ștrand"),
    ("România", "Sibiu", "Turnișor"),
    ("România", "Sibiu", "Gușterița"),

    # Arad
    ("România", "Arad", "Centru"),
    ("România", "Arad", "Aradul Nou"),
    ("România", "Arad", "Subcetate"),
    ("România", "Arad", "Bujac"),
    ("România", "Arad", "Confecții"),
    ("România", "Arad", "Micalaca"),
    ("România", "Arad", "Vlaicu"),

    # Pitești
    ("România", "Pitești", "Centru"),
    ("România", "Pitești", "Războieni"),
    ("România", "Pitești", "Trivale"),
    ("România", "Pitești", "Tudor Vladimirescu"),
    ("România", "Pitești", "Găvana"),
    ("România", "Pitești", "Craiovei"),
    ("România", "Pitești", "Prundu"),

    # Bacău
    ("România", "Bacău", "Centru"),
    ("România", "Bacău", "Cornișa"),
    ("România", "Bacău", "Aviatori"),
    ("România", "Bacău", "Republicii"),
    ("România", "Bacău", "9 Mai"),
    ("România", "Bacău", "CFR"),

    # Suceava, Târgu Mureș, Baia Mare, Buzău — central + 1-2 cartiere fiecare
    ("România", "Suceava", "Centru"),
    ("România", "Suceava", "Burdujeni"),
    ("România", "Suceava", "Obcine"),
    ("România", "Suceava", "Areni"),
    ("România", "Târgu Mureș", "Centru"),
    ("România", "Târgu Mureș", "Tudor Vladimirescu"),
    ("România", "Târgu Mureș", "Dâmbu Pietros"),
    ("România", "Târgu Mureș", "Cornișa"),
    ("România", "Baia Mare", "Centru"),
    ("România", "Baia Mare", "Săsar"),
    ("România", "Baia Mare", "Republicii"),
    ("România", "Baia Mare", "Vasile Alecsandri"),
    ("România", "Buzău", "Centru"),
    ("România", "Buzău", "Micro 14"),
    ("România", "Buzău", "Dorobanți"),
    ("România", "Buzău", "Crâng"),

    # Brăila, Râmnicu Vâlcea, Drobeta-Turnu Severin, Satu Mare
    ("România", "Brăila", "Centru"),
    ("România", "Brăila", "Hipodrom"),
    ("România", "Brăila", "Lacu Dulce"),
    ("România", "Râmnicu Vâlcea", "Centru"),
    ("România", "Râmnicu Vâlcea", "Ostroveni"),
    ("România", "Râmnicu Vâlcea", "Nord"),
    ("România", "Drobeta-Turnu Severin", "Centru"),
    ("România", "Drobeta-Turnu Severin", "Crihala"),
    ("România", "Satu Mare", "Centru"),
    ("România", "Satu Mare", "Micro 17"),
    ("România", "Satu Mare", "Carpați"),
]
